<a href="https://colab.research.google.com/github/alexandrufalk/tensorflow/blob/Master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow fundamentals

TensorFlow Fundamentals

Introduction to tensors (creating tensors)

Getting information from tensors (tensor attributes)

Manipulating tensors (tensor operations)

Tensors and NumPy

Using @tf.function (a way to speed up your regular Python functions)

Using GPUs with TensorFlow

## Introduction to Ternsors


In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [10]:
# Create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [11]:
# Check the number of dimensions of a tesors
scalar.ndim

0

In [12]:
# Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [13]:
# Check the number of dimensions of a vector
vector.ndim

1

In [14]:
# Create a matrix
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [15]:
# Check the number of dimensions of a matrix
matrix.ndim

2

In [16]:
# Create another matrix
matrix2=tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype=tf.float16) #specify the data type
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [17]:
# Check the number of dimensions of  matrix2
matrix2.ndim

2

In [18]:
# Let's create a tensor
tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [19]:
# Check the number of dimensions of tensor
tensor.ndim

3

-Scalar:a single number
-Vector: a number with direction (e.g wind speed an direction)
-Matrix: a 2-dimensional array of numbers
-Tensor: an n-dimensional array of numbers


# Creating tensors tf.Variable

In [20]:
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [21]:
# Change element with .assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [23]:
# Try to change unchangeble tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

 # Creating random tensors


**Note** Rarely in practice will be needed to decide whether to use 'tf.constant' or 'tf.Variable' to create tensors, as TensorFlow does this. However, if in doubt, use 'tf.constant' and change it later if needed

In [24]:
# Creating 2 random (but the same) tensors
random_1=tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2=random_2.normal(shape=(3,2))
# Are they equal?
random_1,random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle the order of elemets in a tesor

In [25]:
#Shuffle a tensor
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
not_shuffled
# Shuffle
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Shuffle
tf.random.shuffle(not_shuffled,seed=42)

In [26]:
# To have tensor in the same order, we have to use global level radom seeds and operation level random seed
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled,seed=42) #operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

# Other ways to makes tesors

In [27]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [28]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turn Numpy arrays into tensors
Difference between NumPy arrays and TesnsorFlow tensors is that tensors can be run on a GPU (much faster numerical computing)

In [5]:
import numpy as np
numpy_a=np.arange(1,25, dtype=np.int32)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [30]:
A=tf.constant(numpy_a,shape=(2,3,4))
B=tf.constant(numpy_a)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

# Getting information from tesnors

There will be times when you'll want to get different pieces of information from your tensors, in particuluar, you should know the following tensor vocabulary:

**Shape**: The length (number of elements) of each of the dimensions of a tensor.

**Rank**: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.

**Axis** or Dimension: A particular dimension of a tensor.

**Size**: The total number of items in the tensor.

You'll use these especially when you're trying to line up the shapes of your data to the shapes of your model. For example, making sure the shape of your image tensors are the same shape as your models input layer.

We've already seen one of these before using the ndim attribute. Let's see the rest.

In [31]:
# Create a Rank 4 tesor (4 dimensions)
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

In [33]:

# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


# Indexing tensors
Tensors can be indexed just like Pythone lists.

In [ ]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

In [ ]:

# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

In [ ]:

# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

can be achieve the same using tf.expand_dims().

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0)

In [ ]:
rank_2_tensor


# Manipulating tensors (tensors operations)

Basic Operations

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

In [ ]:
# Original tensor unchanged
tensor


In [ ]:

# Multiplication (known as element-wise multiplication)
tensor * 10


In [ ]:

# Subtraction
tensor - 10


In [ ]:
# Use the tensorflow function equivalent of the '*' (multiply) operator
tf.multiply(tensor, 10)

In [ ]:

# The original tensor is still unchanged
tensor

To speed up operations use tensorsFlow operations

To keep changes need to alocate tensor=tf.multiply(tensor, 10)

# Matrix mutliplication

One of the most common operations in machine learning algorithms is matrix multiplication.

TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.

In [ ]:
#Matrix multiplication
tf.matmul(tensor,tensor)

In [ ]:
tensor*tensor

In [ ]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

In [21]:

# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:

# Try to matrix multiply them (will error)
X @ Y

Trying to matrix multiply two tensors with the shape (3, 2) errors because the inner dimensions don't match.

We need to either:

Reshape X to (2, 3) so it's (2, 3) @ (3, 2).
Reshape Y to (3, 2) so it's (3, 2) @ (2, 3).
We can do this with either:

tf.reshape() - allows us to reshape a tensor into a defined shape.
tf.transpose() - switches the dimensions of a given tensor.


In [ ]:
tf.reshape(Y,shape=(2,3))

In [ ]:
X@tf.reshape(Y,shape=(2,3))

In [ ]:
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

In [ ]:
# transpose a matrix

X,tf.transpose(X),tf.reshape(X,shape=(2,3))

In [ ]:

# Try matrix multiplication
tf.matmul(tf.transpose(X), Y)

# The dot product
Multiplying matrices by eachother is also referred to as the dot product.

You can perform the tf.matmul() operation using tf.tensordot().

In [22]:
# Perform the dot product on X and Y (requires X to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [25]:

# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:

# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

In [ ]:

# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

generally, whenever performing a matrix multiplication and the shapes of two matrices don't line up, you will transpose (not reshape) one of them in order to line them up.

# Changing the datatype of a tensor

In [ ]:
tf.__version__

In [ ]:

# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

In [ ]:

# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

In [ ]:
# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C


# Aggregation tensors
-condensing them drom multiple values down to a smaller amount of values

In [34]:
# Get the absolut values
D=tf.constant([-1,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 10], dtype=int32)>

Finding the min, max, mean, sum (aggregation)
tf.reduce_min() - find the minimum value in a tensor.

tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).

tf.reduce_mean() - find the mean of all elements in a tensor.

tf.reduce_sum() - find the sum of all elements in a tensor.

Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().

---



In [35]:

# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([84,  8, 65, 97, 42, 96,  9, 50, 51, 37, 46, 31, 36, 83, 49, 29, 53,
       76, 80, 47, 83, 34,  2,  4, 74,  6, 41, 24, 56, 42, 93, 16, 88, 17,
       95, 19, 49, 33, 22, 95, 96, 49, 89, 17, 15, 91, 27, 20, 73, 65])>

In [36]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [37]:
#find th minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [38]:
#find th maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [39]:

# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [40]:

# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2504>

In [43]:
import tensorflow_probability as tfp

In [45]:
#Find the varance and standard deviation
tfp.stats.variance(E)


<tf.Tensor: shape=(), dtype=int64, numpy=873>

In [47]:
tfp.stats.stddev(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.548496>

# Find the postional maximum and minimum

In [7]:
# Create a tensor with 50 values between 0 and 1
tf.random.set_seed(42)
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.53661944, 0.72744591, 0.22339506, 0.76384667, 0.82852045,
       0.25358758, 0.861329  , 0.39347567, 0.77811865, 0.47097742,
       0.74869082, 0.04444929, 0.56852593, 0.8367325 , 0.9211386 ,
       0.67754704, 0.49015746, 0.69083172, 0.41331934, 0.10981572,
       0.79459674, 0.1467446 , 0.51647365, 0.84416432, 0.36250444,
       0.32794633, 0.32454498, 0.29338173, 0.53271679, 0.35684422,
       0.732162  , 0.54080795, 0.66198827, 0.30443099, 0.04732018,
       0.34419597, 0.03172055, 0.95520204, 0.19575637, 0.6981966 ,
       0.73256952, 0.40613891, 0.03099098, 0.19752935, 0.56879685,
       0.85579448, 0.655894  , 0.69552454, 0.62253858, 0.33212208])>

In [51]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=44>

In [54]:
# Index of our larger value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float64, numpy=0.9751444306063499>

In [56]:
#Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float64, numpy=0.9751444306063499>

In [57]:
#Find the positional minimal
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=37>

In [8]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}")
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}")
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 37
The maximum value of F is: 0.95520203901915
Using tf.argmax() to index F, the maximum value of F is: 0.95520203901915
Are the two max values the same (they should be)? True


In [60]:
# Squeezing a tensor (removing all single dimensions)
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [61]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [62]:
G_squeezed=tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

# One-hot encoding

In [63]:

# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [64]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="one", off_value="zero")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'one', b'zero', b'zero', b'zero'],
       [b'zero', b'one', b'zero', b'zero'],
       [b'zero', b'zero', b'one', b'zero'],
       [b'zero', b'zero', b'zero', b'one']], dtype=object)>

# Squaring, log, square root

In [67]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [69]:
#Square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [70]:
# Square root

In [72]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [74]:
# Find the log
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and Numpy



In [75]:
# Create a tensor directly from a NumPy array

In [76]:
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [78]:
# Convert to Numpy
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [79]:
# Convert tensor J to NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [81]:
J.numpy()[1]

7.0

In [82]:

# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Using @tf.function

In [9]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [10]:

# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

no difference between the above two functions (the decorated one and the non-decorated one)
Much of the difference happens behind the scenes. One of the main ones being potential code speed-ups where possible.

# Finding access to GPUs

In [84]:
print(tf.config.list_physical_devices())

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


If you're running in Google Colab, you can access a GPU by going to Runtime -> Change Runtime Type -> Select GPU

In [ ]:

!nvidia-smi

# Exercises

In [16]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300].
H=tf.random.uniform(shape=[5,300],minval=0,maxval=1)
H


TensorShape([5, 300])

In [14]:
I=tf.random.uniform(shape=[5,300],minval=0,maxval=1)
I

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.7413678 , 0.62854624, 0.01738465, ..., 0.4851334 , 0.21059811,
        0.25082767],
       [0.10842848, 0.48783147, 0.8240961 , ..., 0.9204427 , 0.36046863,
        0.28176582],
       [0.7326695 , 0.46489418, 0.13622475, ..., 0.28130388, 0.63987684,
        0.9987265 ],
       [0.01447165, 0.7845044 , 0.33475304, ..., 0.56194997, 0.0209924 ,
        0.1740731 ],
       [0.90936875, 0.19861352, 0.9481231 , ..., 0.3573054 , 0.13161755,
        0.22565222]], dtype=float32)>

In [17]:
# Multiply the two tensors you created in 3 using matrix multiplication
tf.matmul(H,tf.transpose(I))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[70.72622 , 74.726906, 71.275734, 72.729385, 74.68822 ],
       [75.72979 , 77.85751 , 74.78479 , 79.52106 , 79.29985 ],
       [71.49379 , 71.81675 , 70.81471 , 73.937904, 70.17963 ],
       [67.994896, 72.3465  , 67.8546  , 69.63492 , 71.5575  ],
       [69.66651 , 68.144295, 70.59231 , 71.62952 , 73.04637 ]],
      dtype=float32)>

In [19]:
tf.matmul(H,tf.reshape(I,shape=[300,5]))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[74.91705 , 77.39891 , 70.447624, 74.581726, 73.653015],
       [80.62897 , 75.43423 , 73.656235, 75.584206, 76.39882 ],
       [73.87909 , 70.52286 , 67.78756 , 72.999   , 71.34606 ],
       [72.17226 , 71.10154 , 68.0393  , 68.37593 , 67.39522 ],
       [70.51744 , 71.153206, 69.47278 , 74.247086, 69.8927  ]],
      dtype=float32)>

In [26]:
tf.tensordot(H,tf.transpose(I),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[70.72622 , 74.726906, 71.275734, 72.729385, 74.68822 ],
       [75.72979 , 77.85751 , 74.78479 , 79.52106 , 79.29985 ],
       [71.49379 , 71.81675 , 70.81471 , 73.937904, 70.17963 ],
       [67.994896, 72.3465  , 67.8546  , 69.63492 , 71.5575  ],
       [69.66651 , 68.144295, 70.59231 , 71.62952 , 73.04637 ]],
      dtype=float32)>

In [31]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3]
J=tf.random.uniform(shape=[224,224,3],minval=0,maxval=1)
J.ndim,J

(3,
 <tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[0.14241445, 0.40161622, 0.33360183],
         [0.6816542 , 0.69087017, 0.22069418],
         [0.61336195, 0.9588975 , 0.3314948 ],
         ...,
         [0.21534526, 0.8758553 , 0.90849984],
         [0.913136  , 0.3300879 , 0.21957576],
         [0.294909  , 0.51060224, 0.41247094]],
 
        [[0.24516141, 0.0526433 , 0.8009639 ],
         [0.39559937, 0.91123044, 0.66148484],
         [0.62018025, 0.13185847, 0.2584139 ],
         ...,
         [0.69155025, 0.35061288, 0.7918345 ],
         [0.71887565, 0.13187587, 0.6776898 ],
         [0.91522217, 0.72013485, 0.5736792 ]],
 
        [[0.32997262, 0.01919758, 0.7673421 ],
         [0.37867343, 0.09564745, 0.07906318],
         [0.7100911 , 0.934427  , 0.5622425 ],
         ...,
         [0.8063401 , 0.53997624, 0.9590297 ],
         [0.7728716 , 0.5758432 , 0.53311133],
         [0.00398016, 0.15231979, 0.6468185 ]],
 
        ...,
 
        [[0.3400538 , 0.4092

In [32]:
#min and max
print(f"The min value of J is : {tf.reduce_min(J).numpy()}")
print(f"The min value of J is at position: {tf.math.argmin(J)}")
print(f"The maximum value of J is : {tf.reduce_max(J).numpy()}")
print(f"The maximum value of J is at position: {tf.math.argmax(J).numpy()}")


The min value of J is : 4.172325134277344e-06
The min value of J is at position: [[ 78 151 209]
 [113 208  94]
 [140 181 107]
 [ 27  63  41]
 [125 161  52]
 [210  11 191]
 [  1 161  72]
 [209   2 140]
 [ 97  60  23]
 [112 144 201]
 [121 170 147]
 [ 92  93 212]
 [ 94 116  92]
 [ 92 197 146]
 [152  77 204]
 [199 162  31]
 [ 95 170 176]
 [173 141 204]
 [176  70 106]
 [117   8  79]
 [ 65  48 217]
 [ 65 182  97]
 [111  36 148]
 [ 50 181 183]
 [ 67 184 124]
 [ 21 100  49]
 [184 218 154]
 [166  29 125]
 [ 82  55 174]
 [214 178  81]
 [ 79  57   2]
 [ 86 203 193]
 [167 176 141]
 [ 84 155  83]
 [221 195 196]
 [190 194  98]
 [112  78 177]
 [ 28  94 125]
 [ 93 152  33]
 [ 24  55 171]
 [192  71  66]
 [112   5  41]
 [171   2  71]
 [  4  43  67]
 [ 53  47 193]
 [ 49  78 152]
 [104 110  69]
 [186  79 172]
 [183 140  76]
 [210 171 131]
 [218 223  51]
 [206   2  79]
 [193 210 184]
 [  9  64 186]
 [ 22 212  32]
 [215  32  99]
 [162  29 216]
 [190 125 120]
 [140 215 215]
 [176 216  81]
 [135  48  27]
 [  

In [33]:
#Create a tensor with shape [10]
K=tf.constant([1,2,3,4,5,6,7,8,9,10])
K.shape

TensorShape([10])

In [35]:
#One-hot encode the tensor
tf.one_hot(K,depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>