<a href="https://colab.research.google.com/github/alexandrufalk/tensorflow/blob/Master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow fundamentals

TensorFlow Fundamentals

Introduction to tensors (creating tensors)

Getting information from tensors (tensor attributes)

Manipulating tensors (tensor operations)

Tensors and NumPy

Using @tf.function (a way to speed up your regular Python functions)

Using GPUs with TensorFlow

## Introduction to Ternsors


In [9]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [10]:
# Create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [11]:
# Check the number of dimensions of a tesors
scalar.ndim

0

In [12]:
# Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [13]:
# Check the number of dimensions of a vector
vector.ndim

1

In [14]:
# Create a matrix
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [15]:
# Check the number of dimensions of a matrix
matrix.ndim

2

In [16]:
# Create another matrix
matrix2=tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype=tf.float16) #specify the data type
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [17]:
# Check the number of dimensions of  matrix2
matrix2.ndim

2

In [18]:
# Let's create a tensor
tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [19]:
# Check the number of dimensions of tensor
tensor.ndim

3

-Scalar:a single number
-Vector: a number with direction (e.g wind speed an direction)
-Matrix: a 2-dimensional array of numbers
-Tensor: an n-dimensional array of numbers


# Creating tensors tf.Variable

In [20]:
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [21]:
# Change element with .assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [23]:
# Try to change unchangeble tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

 # Creating random tensors


**Note** Rarely in practice will be needed to decide whether to use 'tf.constant' or 'tf.Variable' to create tensors, as TensorFlow does this. However, if in doubt, use 'tf.constant' and change it later if needed

In [24]:
# Creating 2 random (but the same) tensors
random_1=tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2=random_2.normal(shape=(3,2))
# Are they equal?
random_1,random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle the order of elemets in a tesor

In [25]:
#Shuffle a tensor
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
not_shuffled
# Shuffle
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Shuffle
tf.random.shuffle(not_shuffled,seed=42)

In [26]:
# To have tensor in the same order, we have to use global level radom seeds and operation level random seed
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled,seed=42) #operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

# Other ways to makes tesors

In [27]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [28]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turn Numpy arrays into tensors
Difference between NumPy arrays and TesnsorFlow tensors is that tensors can be run on a GPU (much faster numerical computing)

In [29]:
import numpy as np
numpy_a=np.arange(1,25, dtype=np.int32)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [30]:
A=tf.constant(numpy_a,shape=(2,3,4))
B=tf.constant(numpy_a)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

# Getting information from tesnors

There will be times when you'll want to get different pieces of information from your tensors, in particuluar, you should know the following tensor vocabulary:

**Shape**: The length (number of elements) of each of the dimensions of a tensor.

**Rank**: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.

**Axis** or Dimension: A particular dimension of a tensor.

**Size**: The total number of items in the tensor.

You'll use these especially when you're trying to line up the shapes of your data to the shapes of your model. For example, making sure the shape of your image tensors are the same shape as your models input layer.

We've already seen one of these before using the ndim attribute. Let's see the rest.

In [31]:
# Create a Rank 4 tesor (4 dimensions)
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

In [33]:

# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


# Indexing tensors
Tensors can be indexed just like Pythone lists.

In [ ]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

In [ ]:

# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

In [ ]:

# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

can be achieve the same using tf.expand_dims().

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0)

In [ ]:
rank_2_tensor


# Manipulating tensors (tensors operations)

Basic Operations

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

In [ ]:
# Original tensor unchanged
tensor


In [ ]:

# Multiplication (known as element-wise multiplication)
tensor * 10


In [ ]:

# Subtraction
tensor - 10


In [ ]:
# Use the tensorflow function equivalent of the '*' (multiply) operator
tf.multiply(tensor, 10)

In [ ]:

# The original tensor is still unchanged
tensor

To speed up operations use tensorsFlow operations

To keep changes need to alocate tensor=tf.multiply(tensor, 10)

# Matrix mutliplication

One of the most common operations in machine learning algorithms is matrix multiplication.

TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.

In [ ]:
#Matrix multiplication
tf.matmul(tensor,tensor)

In [ ]:
tensor*tensor

In [ ]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

In [ ]:

# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

In [ ]:

# Try to matrix multiply them (will error)
X @ Y

Trying to matrix multiply two tensors with the shape (3, 2) errors because the inner dimensions don't match.

We need to either:

Reshape X to (2, 3) so it's (2, 3) @ (3, 2).
Reshape Y to (3, 2) so it's (3, 2) @ (2, 3).
We can do this with either:

tf.reshape() - allows us to reshape a tensor into a defined shape.
tf.transpose() - switches the dimensions of a given tensor.


In [ ]:
tf.reshape(Y,shape=(2,3))

In [ ]:
X@tf.reshape(Y,shape=(2,3))

In [ ]:
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

In [ ]:
# transpose a matrix

X,tf.transpose(X),tf.reshape(X,shape=(2,3))

In [ ]:

# Try matrix multiplication
tf.matmul(tf.transpose(X), Y)

# The dot product
Multiplying matrices by eachother is also referred to as the dot product.

You can perform the tf.matmul() operation using tf.tensordot().

In [ ]:
# Perform the dot product on X and Y (requires X to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

In [ ]:

# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

In [ ]:

# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

In [ ]:

# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

generally, whenever performing a matrix multiplication and the shapes of two matrices don't line up, you will transpose (not reshape) one of them in order to line them up.

# Changing the datatype of a tensor

In [ ]:
tf.__version__

In [ ]:

# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

In [ ]:

# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

In [ ]:
# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C


# Aggregation tensors
-condensing them drom multiple values down to a smaller amount of values

In [34]:
# Get the absolut values
D=tf.constant([-1,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 10], dtype=int32)>

Finding the min, max, mean, sum (aggregation)
tf.reduce_min() - find the minimum value in a tensor.

tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).

tf.reduce_mean() - find the mean of all elements in a tensor.

tf.reduce_sum() - find the sum of all elements in a tensor.

Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().

---



In [35]:

# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([84,  8, 65, 97, 42, 96,  9, 50, 51, 37, 46, 31, 36, 83, 49, 29, 53,
       76, 80, 47, 83, 34,  2,  4, 74,  6, 41, 24, 56, 42, 93, 16, 88, 17,
       95, 19, 49, 33, 22, 95, 96, 49, 89, 17, 15, 91, 27, 20, 73, 65])>

In [36]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [37]:
#find th minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [38]:
#find th maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [39]:

# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [40]:

# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2504>

In [43]:
import tensorflow_probability as tfp

In [45]:
#Find the varance and standard deviation
tfp.stats.variance(E)


<tf.Tensor: shape=(), dtype=int64, numpy=873>

In [47]:
tfp.stats.stddev(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.548496>

# Find the postional maximum and minimum

In [50]:
# Create a tensor with 50 values between 0 and 1
tf.random.set_seed(42)
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.90433545, 0.4871472 , 0.64472278, 0.7383281 , 0.08891739,
       0.93419425, 0.92494973, 0.56228216, 0.08046008, 0.4449457 ,
       0.12096545, 0.41147276, 0.21765425, 0.27679662, 0.31603597,
       0.87088986, 0.75309711, 0.37245453, 0.47359986, 0.49869268,
       0.73111857, 0.08170133, 0.26812859, 0.97235473, 0.56008698,
       0.32366338, 0.2739379 , 0.92781249, 0.87402483, 0.80582197,
       0.34969677, 0.20673054, 0.9244908 , 0.92336533, 0.15901588,
       0.25649669, 0.35892824, 0.03680106, 0.92499121, 0.33026723,
       0.72142681, 0.3858852 , 0.81180957, 0.6038778 , 0.97514443,
       0.13515483, 0.49644054, 0.60386645, 0.45500948, 0.64116496])>

In [51]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=44>

In [54]:
# Index of our larger value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float64, numpy=0.9751444306063499>

In [56]:
#Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float64, numpy=0.9751444306063499>

In [57]:
#Find the positional minimal
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=37>